version: '2'
services:
  jhipster_study-app:
    image: jhipster_study
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipster_study-postgresql:5432/jhipster_study
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipster_study-postgresql:
    extends:
      file: postgresql.yml
      service: jhipster_study-postgresql
